### ISSUE TITLE
[Bug] FFA mode Home key doesn't turn on FFA mode on my Laptop

### ISSUE THREAD

**Issue by zMega26** [shawnjbragdon-0/GameSense-Rewritten#1]
Is there a way to fix it, or change the keybind to something more accessible?

**Comment by shawnjbragdon-0** [comment]
Remember to change the key binding in the autoexec script. If that doesn't work, consider replying to this thread with the laptop you are using.

**Comment by zMega26** [comment]
> Remember to change the key binding in the autoexec script. If that doesn't work, consider replying to this thread with the laptop you are using.

Copied the settings file to the autoexec and changed the keybinding and it worked. I appreciate it a lot. Also if you're open to suggestions, I'd suggest making the Aimbot random, but the script is still a 10/10. Thanks for the help and for making the script :)

**Comment by shawnjbragdon-0** [comment]
I've gotten several reports that the aiming status key hasn't worked for KeyCode so I will take a look at the code.

**Comment by zMega26** [comment]
> I've gotten several reports that the aiming status key hasn't worked for KeyCode so I will take a look at the code.

Thank you :)
